from .extract import extract_single_bass_line, extract_all_bass_lines
from .extractor_class import BassLineExtractor
from .parallel_processing import BatchBasslineExtractor, extract_batch_basslines
from .parallel_processing import main as main_batch